### ISSUE TITLE
Fails to build on CentOS 6 

### ISSUE THREAD

**Issue by JPaulMora** [fancoder/node-multi-hashing#2]
```
$ npm install multi-hashing
|
> multi-hashing@0.0.4 install /sata/node_modules/multi-hashing
> node-gyp rebuild

make: Entering directory `/sata/node_modules/multi-hashing/build'
make: *** No rule to make target `/.node-gyp/0.10.46/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/sata/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-642.1.1.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /sata/node_modules/multi-hashing
gyp ERR! node -v v0.10.46
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-642.1.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "multi-hashing"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /sata/npm-debug.log
```

**Comment by mooleshacat** [comment]
similar error on Debian 9

**Edit:**
nevermind didnt compile :(
